"""
TPA Database Integration - MVP Version

Simple database integration for TPA agentic interface to persist interactions
and update treatment records.
"""

import json
import logging
from typing import Dict, Any, Optional, List
from datetime import datetime, timedelta
from sqlalchemy.orm import Session
from sqlalchemy import text

logger = logging.getLogger(__name__)

class TPADatabaseIntegration:
    """
    MVP Database Integration for TPA agentic interface.
    
    Provides:
    - Persist TPA interactions
    - Update treatment records with TPA data
    - Retrieve patient context
    - Basic analytics
    """
    
    def __init__(self, db_session: Session):
        """Initialize with database session"""
        self.db = db_session
        self.logger = logging.getLogger(__name__)
    
    def log_tpa_interaction(
        self,
        patient_id: str,
        operation_type: str,
        trigger_event: str,
        urgency_level: str,
        confidence_score: float,
        risk_level: str,
        escalation_level: str,
        recommendations: List[str],
        next_actions: List[str],
        patient_context_snapshot: Dict[str, Any],
        operation_result: Any,
        treatment_record_id: Optional[str] = None,
        additional_data: Optional[Dict[str, Any]] = None,
        response_time_ms: Optional[int] = None
    ) -> Optional[str]:
        """
        Log a TPA interaction to the database.
        
        Args:
            patient_id: Patient identifier
            operation_type: Type of operation performed
            trigger_event: What triggered the interaction
            urgency_level: Urgency level
            confidence_score: TPA confidence score
            risk_level: Identified risk level
            escalation_level: Required escalation level
            recommendations: TPA recommendations
            next_actions: TPA next actions
            patient_context_snapshot: Patient context data
            operation_result: Result of the operation
            treatment_record_id: Associated treatment record ID
            additional_data: Additional context data
            response_time_ms: Response time in milliseconds
            
        Returns:
            Interaction ID if successful, None otherwise
        """
        try:
            # Import models here to avoid circular imports
            from App.backend_2.models.sql_models.clinical_models import TPAInteraction
            
            # Create interaction record
            interaction = TPAInteraction(
                patient_id=patient_id,
                treatment_record_id=treatment_record_id,
                operation_type=operation_type,
                trigger_event=trigger_event,
                urgency_level=urgency_level,
                confidence_score=confidence_score,
                risk_level=risk_level,
                escalation_level=escalation_level,
                recommendations=json.dumps(recommendations),
                next_actions=json.dumps(next_actions),
                patient_context_snapshot=json.dumps(patient_context_snapshot),
                additional_data=json.dumps(additional_data) if additional_data else None,
                operation_result=json.dumps(operation_result),
                response_time_ms=response_time_ms,
                requires_pima_action=escalation_level != "none",
                interaction_timestamp=datetime.now()
            )
            
            # Add to database
            self.db.add(interaction)
            self.db.commit()
            
            # Refresh to get the ID
            self.db.refresh(interaction)
            
            self.logger.info(f"Logged TPA interaction {interaction.id} for patient {patient_id}")
            return str(interaction.id)
            
        except Exception as e:
            self.logger.error(f"Error logging TPA interaction: {e}")
            self.db.rollback()
            return None
    
    def update_treatment_record_tpa_data(
        self,
        treatment_record_id: str,
        tpa_generated: bool = True,
        tpa_confidence_score: Optional[float] = None,
        tpa_risk_level: Optional[str] = None,
        tpa_escalation_level: Optional[str] = None,
        tpa_recommendations: Optional[List[str]] = None,
        tpa_next_actions: Optional[List[str]] = None
    ) -> bool:
        """
        Update treatment record with TPA data.
        
        Args:
            treatment_record_id: Treatment record ID
            tpa_generated: Whether plan was generated by TPA
            tpa_confidence_score: TPA confidence score
            tpa_risk_level: Current risk level
            tpa_escalation_level: Escalation level
            tpa_recommendations: TPA recommendations
            tpa_next_actions: TPA next actions
            
        Returns:
            True if successful, False otherwise
        """
        try:
            # Import models here to avoid circular imports
            from App.backend_2.models.sql_models.clinical_models import TreatmentRecord
            
            # Get treatment record
            treatment = self.db.query(TreatmentRecord).filter(
                TreatmentRecord.id == treatment_record_id
            ).first()
            
            if not treatment:
                self.logger.warning(f"Treatment record {treatment_record_id} not found")
                return False
            
            # Update TPA fields
            treatment.tpa_generated = tpa_generated
            treatment.tpa_last_assessment = datetime.now()
            
            if tpa_confidence_score is not None:
                treatment.tpa_confidence_score = tpa_confidence_score
            
            if tpa_risk_level is not None:
                treatment.tpa_risk_level = tpa_risk_level
            
            if tpa_escalation_level is not None:
                treatment.tpa_escalation_level = tpa_escalation_level
            
            if tpa_recommendations is not None:
                treatment.tpa_recommendations = json.dumps(tpa_recommendations)
            
            if tpa_next_actions is not None:
                treatment.tpa_next_actions = json.dumps(tpa_next_actions)
            
            # Commit changes
            self.db.commit()
            
            self.logger.info(f"Updated treatment record {treatment_record_id} with TPA data")
            return True
            
        except Exception as e:
            self.logger.error(f"Error updating treatment record TPA data: {e}")
            self.db.rollback()
            return False
    
    def get_patient_tpa_context(
        self,
        patient_id: str,
        limit: int = 10
    ) -> Dict[str, Any]:
        """
        Get patient's TPA context from recent interactions.
        
        Args:
            patient_id: Patient identifier
            limit: Maximum number of interactions to retrieve
            
        Returns:
            Patient TPA context
        """
        try:
            # Import models here to avoid circular imports
            from App.backend_2.models.sql_models.clinical_models import TPAInteraction
            
            # Get recent interactions
            interactions = self.db.query(TPAInteraction).filter(
                TPAInteraction.patient_id == patient_id
            ).order_by(
                TPAInteraction.interaction_timestamp.desc()
            ).limit(limit).all()
            
            # Build context
            context = {
                "patient_id": patient_id,
                "recent_interactions": [],
                "current_risk_level": "low",
                "last_assessment": None,
                "escalation_history": []
            }
            
            for interaction in interactions:
                interaction_data = {
                    "id": str(interaction.id),
                    "operation_type": interaction.operation_type,
                    "timestamp": interaction.interaction_timestamp.isoformat(),
                    "confidence_score": float(interaction.confidence_score) if interaction.confidence_score else None,
                    "risk_level": interaction.risk_level,
                    "escalation_level": interaction.escalation_level,
                    "recommendations": json.loads(interaction.recommendations) if interaction.recommendations else [],
                    "next_actions": json.loads(interaction.next_actions) if interaction.next_actions else []
                }
                
                context["recent_interactions"].append(interaction_data)
                
                # Update current risk level (most recent)
                if not context["last_assessment"]:
                    context["current_risk_level"] = interaction.risk_level
                    context["last_assessment"] = interaction.interaction_timestamp.isoformat()
                
                # Track escalations
                if interaction.escalation_level != "none":
                    context["escalation_history"].append({
                        "timestamp": interaction.interaction_timestamp.isoformat(),
                        "level": interaction.escalation_level,
                        "operation": interaction.operation_type
                    })
            
            return context
            
        except Exception as e:
            self.logger.error(f"Error getting patient TPA context: {e}")
            return {
                "patient_id": patient_id,
                "error": str(e),
                "recent_interactions": [],
                "current_risk_level": "unknown",
                "last_assessment": None,
                "escalation_history": []
            }
    
    def get_tpa_analytics(
        self,
        days: int = 30
    ) -> Dict[str, Any]:
        """
        Get basic TPA analytics.
        
        Args:
            days: Number of days to analyze
            
        Returns:
            Analytics data
        """
        try:
            # Import models here to avoid circular imports
            from App.backend_2.models.sql_models.clinical_models import TPAInteraction
            
            # Calculate date threshold
            threshold_date = datetime.now() - timedelta(days=days)
            
            # Get interactions in date range
            interactions = self.db.query(TPAInteraction).filter(
                TPAInteraction.interaction_timestamp >= threshold_date
            ).all()
            
            # Calculate analytics
            total_interactions = len(interactions)
            operations_count = {}
            risk_levels_count = {}
            escalations_count = 0
            
            for interaction in interactions:
                # Count operations
                op_type = interaction.operation_type
                operations_count[op_type] = operations_count.get(op_type, 0) + 1
                
                # Count risk levels
                risk_level = interaction.risk_level
                risk_levels_count[risk_level] = risk_levels_count.get(risk_level, 0) + 1
                
                # Count escalations
                if interaction.escalation_level != "none":
                    escalations_count += 1
            
            # Calculate average confidence
            confidence_scores = [
                float(interaction.confidence_score) 
                for interaction in interactions 
                if interaction.confidence_score is not None
            ]
            avg_confidence = sum(confidence_scores) / len(confidence_scores) if confidence_scores else 0
            
            return {
                "period_days": days,
                "total_interactions": total_interactions,
                "operations_breakdown": operations_count,
                "risk_levels_breakdown": risk_levels_count,
                "escalations_count": escalations_count,
                "escalation_rate": escalations_count / total_interactions if total_interactions > 0 else 0,
                "average_confidence": round(avg_confidence, 2)
            }
            
        except Exception as e:
            self.logger.error(f"Error getting TPA analytics: {e}")
            return {
                "error": str(e),
                "period_days": days,
                "total_interactions": 0,
                "operations_breakdown": {},
                "risk_levels_breakdown": {},
                "escalations_count": 0,
                "escalation_rate": 0,
                "average_confidence": 0
            }
    
    def cleanup_old_interactions(self, days_to_keep: int = 90) -> int:
        """
        Clean up old TPA interactions.
        
        Args:
            days_to_keep: Number of days to keep interactions
            
        Returns:
            Number of interactions deleted
        """
        try:
            # Import models here to avoid circular imports
            from App.backend_2.models.sql_models.clinical_models import TPAInteraction
            
            # Calculate cutoff date
            cutoff_date = datetime.now() - timedelta(days=days_to_keep)
            
            # Delete old interactions
            deleted_count = self.db.query(TPAInteraction).filter(
                TPAInteraction.interaction_timestamp < cutoff_date
            ).delete()
            
            self.db.commit()
            
            self.logger.info(f"Cleaned up {deleted_count} old TPA interactions")
            return deleted_count
            
        except Exception as e:
            self.logger.error(f"Error cleaning up old interactions: {e}")
            self.db.rollback()
            return 0
